version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    command: -p 5432
    env_file:
      - ./.env

  test_db:
    image: postgres:15-alpine
    ports:
      - "6000:6000"
    command: -p 6000
    env_file:
      - ./.env

  backend:
    image: hrushon/your_salary:workflow
    build: ../
    restart: always
    depends_on:
      - db
      - test_db
    env_file:
      - ./.env
    command: pytest

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  db_value:
