name: test backend

on:
  pull_request:
    branches:
    - main

env:
  DEBUG: False
  DEVELOPMENT: True
  POSTGRES_DB: your_salary_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  DB_HOST: db
  DB_PORT: 5432
  POSTGRES_DB_TEST: test_db
  DB_HOST_TEST: localhost
  DB_PORT_TEST: 6000

jobs:
  tests_with_flake8_and_pytest:
    name: Check app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.3.2
        poetry install --with test
    - name: Create .env file
      run: |
        touch .env
        echo DEBUG=$DEBUG >> .env
        echo DEVELOPMENT=$DEVELOPMENT >> .env
        echo POSTGRES_DB=$POSTGRES_DB >> .env
        echo POSTGRES_USER=$POSTGRES_USER >> .env
        echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD >> .env
        echo DB_HOST=$DB_HOST >> .env
        echo DB_PORT=$DB_PORT >> .env
        echo POSTGRES_DB_TEST=$POSTGRES_DB_TEST >> .env
        echo DB_HOST_TEST=$DB_HOST_TEST >> .env
        echo DB_PORT_TEST=$DB_PORT_TEST >> .env
    - name: Test with Pytest
      run: |
        poetry run pytest
